CREATE DATABASE wordpress;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE ON phpmyadmin.* TO 'pma'@'%' IDENTIFIED BY 'root';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE ON wordpress.* TO 'wp'@'%' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' IDENTIFIED BY 'root' WITH GRANT OPTION;
FLUSH PRIVILEGES;
