apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        - containerPort: 21005
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps-port-21
    port: 21
    targetPort: 21
  - name: ftps-port-21000
    port: 21000
    targetPort: 21000
  - name: ftps-port-21001
    port: 21001
    targetPort: 21001
  - name: ftps-port-21002
    port: 21002
    targetPort: 21002
  - name: ftps-port-21003
    port: 21003
    targetPort: 21003
  - name: ftps-port-21004
    port: 21004
    targetPort: 21004
  - name: ftps-port-21005
    port: 21005
    targetPort: 21005
