apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    template:
        metadata:
            name: mysql
            labels:
                app: mysql
        spec:
            containers:
                - image: mysql
                  name: mysql
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-svc
spec:
    type: ClusterIP
