apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            name: nginx
            labels:
                app: nginx
        spec:
            containers:
                - image: nginx
                  name: nginx
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: conf.d
                        mountPath: "/etc/nginx/"
                        ressources:
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
            volumes:
                - name: conf.d
                  configMap:
                      name: nginx
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
    type: LoadBalancer
    selector:
        app: nginx
    ports:
        - port: 80
          targetPort: 80