apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf
        imagePullPolicy: Never
        volumeMounts:
          - name: docker-socket
            mountPath: "/var/run/docker.sock"
        livenessProbe:
          exec:
            command:
              - /bin/ash
              - /liveness.sh
          initialDelaySeconds: 20
          periodSeconds: 5
      volumes:
      - name: docker-socket
        hostPath:
           path: /var/run/docker.sock
