apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          livenessProbe:
              exec:
                  command:
                      - /bin/ash
                      - /liveness.sh
              initialDelaySeconds: 10
              periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
